### ISSUE TITLE
Wiki Smithing Template Link Change

### ISSUE THREAD

**Issue by IThisGuyHere** [Micalobia/Micahcraft-Datapack#1]
The Smithing Template link on the [Loot Tables](https://github.com/Micalobia/Micahcraft-Datapack/wiki/Loot-Tables) page of the wiki should redirect to [minecraft.wiki](https://minecraft.wiki/w/Smithing_Template) instead of [fandom](https://minecraft.fandom.com/wiki/Smithing_Template)

**Comment by GeneralGoose6941** [comment]
Resolved
